mod app;
pub mod atuin;
mod clipboard;
pub mod commands;
pub mod config;
pub mod logging;
mod updater;

pub use app::run;
pub use atuin::{
    atuin_search, parse_atuin_line, parse_atuin_output, AtuinResult, ExitFilter, SearchFilters,
    TimeRange,
};
pub use config::{get_config_path, load_config, Config, Theme};

#[cfg(test)]
mod type_export_tests {
    use super::{AtuinResult, Config, ExitFilter, SearchFilters, Theme, TimeRange};
    use std::fs;
    use ts_rs::TS;

    #[test]
    fn export_frontend_bindings() {
        let bindings = format!(
            "// This file is generated by src-tauri/src/lib.rs type_export_tests.\n// Run `cargo test` in src-tauri after changing shared Rust DTOs.\n\n{}\n\n{}\n\n{}\n\n{}\n\n{}\n\n{}\n",
            Theme::decl(),
            Config::decl(),
            ExitFilter::decl(),
            TimeRange::decl(),
            SearchFilters::decl(),
            AtuinResult::decl(),
        )
        .replace("type ", "export type ");
        fs::write("../src/bindings.ts", bindings).expect("write generated TypeScript bindings");
    }
}
