// This file is generated by src-tauri/src/lib.rs type_export_tests.
// Run `cargo test` in src-tauri after changing shared Rust DTOs.

export type Theme = "dark" | "light";

export type Config = { 
/**
 * Global shortcut to toggle the window (e.g., "CommandOrControl+Shift+Space")
 */
shortcut: string, 
/**
 * Theme: "dark" or "light" (default: "dark")
 */
theme: Theme, 
/**
 * Maximum number of results to display (default: 20)
 */
max_results: number, 
/**
 * Window width in pixels (default: 700)
 */
window_width: number, };

export type ExitFilter = "success" | "failure";

export type TimeRange = "1h" | "24h" | "7d" | "30d";

export type SearchFilters = { 
/**
 * Filter by directory path
 */
directory: string | null, 
/**
 * Filter by exit code: "success" (0), "failure" (non-0), or None (all)
 */
exit_filter: ExitFilter | null, 
/**
 * Time range: "1h", "24h", "7d", "30d", or None (all)
 */
time_range: TimeRange | null, };

export type AtuinResult = { command: string, exit: string, duration: string, directory: string, time: string, };
